### ISSUE TITLE
Branch `bitname/testnet` `owners` table is incorrect

### ISSUE THREAD

**Issue by btcopenstamp** [stampchain-io/btc_stamps#360]
**Describe the bug**
A single transaction mints multiple items with `mint` op. The transaction has been recorded in the src101valid table, but these items have not been updated in the owners table.

**Branch/Release/Commit Hash of Problem**
Branch bitname/testnet.

**To Reproduce**
1. Using the mint operation to mint multiple items

**Expected behavior**
The `owners` table correctly records the src101 data.

**Comment by vikkkko** [comment]
It may be cause by https://github.com/stampchain-io/btc_stamps/issues/359.
After I fixed [problem](https://github.com/stampchain-io/btc_stamps/issues/359), data is correct in the owners table.

**Comment by btcopenstamp** [comment]
@superboyiii @vikkkko After reindexing with the latest PR’s code (#388), it was found that the issue with the case sensitivity of the tokenId caused incorrect data in the owner table. The owner table did not use tokenid_utf8 as a unique index but instead used tokenid. This issue is related to #372.

```
CREATE TABLE IF NOT EXISTS `owners` (
  `index` INT NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  `p` varchar(32),
  `deploy_hash` VARCHAR(64) NOT NULL,
  `tokenid` varchar(255) NOT NULL,
  `tokenid_utf8` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
  `img` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
  `preowner` varchar(64) COLLATE utf8mb4_bin,
  `owner` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `prim` BOOLEAN DEFAULT NULL,
  `address_data` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
  `address_btc` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
  `address_eth` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
  `txt_data` TEXT DEFAULT NULL COLLATE utf8mb4_bin,
  `expire_timestamp` BIGINT UNSIGNED DEFAULT NULL,
  `last_update` int,
  PRIMARY KEY (`index`),
  UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid`),
  INDEX `id` (`id`),
  INDEX `owner` (`owner`),
  INDEX `p_deploy_hash_tokenid` (`p`,`deploy_hash`,`tokenid`),
  INDEX `p_deploy_hash_tokenid_utf8` (`p`,`deploy_hash`,`tokenid_utf8`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci;
```

owner `tb1qvw44al3dmtqkxpv49lp376dc5pz66nka8u6zpv ` data:
![owner data](https://github.com/user-attachments/assets/5577c7c5-f158-46bd-b9e5-4b8669a04b8b)

more:
```sql
SELECT tokenid_utf8, count(*) cnt
FROM owners
WHERE expire_timestamp > UNIX_TIMESTAMP(NOW())
GROUP BY tokenid_utf8
HAVING	cnt > 1;
```
query result:

| tokenid_utf8                                            | cnt |
|---------------------------------------------------------|-----|
| warirekyakiroeki🇮🇹                                       |   2 |
| ogun’omutimbaganogw’okugyezibwaobubonerotiburihomugasho |   2 |
| wtf                                                     |   2 |
| pepe                                                    |   2 |
| northsat                                                |   2 |
| test                                                    |   2 |
| sos                                                     |   2 |
| makestampgreatagain                                     |   2 |
| bitname                                                 |   2 |
| ibit                                                    |   2 |
| javaeast                                                |   2 |
| jhakaaqueen                                             |   2 |
| styme                                                   |   2 |
| aadil                                                   |   2 |
| fight                                                   |   2 |
| src                                                     |   2 |
| mor                                                     |   2 |
| muhammad                                                |   2 |
| nameless                                                |   2 |
| smoothieb                                               |   2 |
| ruby                                                    |   2 |
| nra                                                     |   2 |
| sea                                                     |   2 |
| yara                                                    |   2 |
| last                                                    |   2 |
| dao                                                     |   2 |
| presidentpepe                                           |   2 |
| run                                                     |   2 |
| plan                                                    |   2 |
| join                                                    |   2 |
| swan                                                    |   2 |
| su7                                                     |   2 |
| gallery                                                 |   2 |
| opeic                                                   |   2 |


I think it would better to replace ``` UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid`),``` with ``` UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid_utf8`),```, and the code needs to be adjusted accordingly.

**Comment by vikkkko** [comment]
> @superboyiii @vikkkko After reindexing with the latest PR’s code (#388), it was found that the issue with the case sensitivity of the tokenId caused incorrect data in the owner table. The owner table did not use tokenid_utf8 as a unique index but instead used tokenid. This issue is related to #372.
> 
> ```
> CREATE TABLE IF NOT EXISTS `owners` (
>   `index` INT NOT NULL,
>   `id` VARCHAR(255) NOT NULL,
>   `p` varchar(32),
>   `deploy_hash` VARCHAR(64) NOT NULL,
>   `tokenid` varchar(255) NOT NULL,
>   `tokenid_utf8` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
>   `img` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
>   `preowner` varchar(64) COLLATE utf8mb4_bin,
>   `owner` varchar(64) COLLATE utf8mb4_bin NOT NULL,
>   `prim` BOOLEAN DEFAULT NULL,
>   `address_data` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
>   `address_btc` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
>   `address_eth` varchar(255) DEFAULT NULL COLLATE utf8mb4_bin,
>   `txt_data` TEXT DEFAULT NULL COLLATE utf8mb4_bin,
>   `expire_timestamp` BIGINT UNSIGNED DEFAULT NULL,
>   `last_update` int,
>   PRIMARY KEY (`index`),
>   UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid`),
>   INDEX `id` (`id`),
>   INDEX `owner` (`owner`),
>   INDEX `p_deploy_hash_tokenid` (`p`,`deploy_hash`,`tokenid`),
>   INDEX `p_deploy_hash_tokenid_utf8` (`p`,`deploy_hash`,`tokenid_utf8`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_ci;
> ```
> 
> owner `tb1qvw44al3dmtqkxpv49lp376dc5pz66nka8u6zpv ` data: ![owner data](https://private-user-images.githubusercontent.com/137025416/362657189-5577c7c5-f158-46bd-b9e5-4b8669a04b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwODM2MjcsIm5iZiI6MTcyNTA4MzMyNywicGF0aCI6Ii8xMzcwMjU0MTYvMzYyNjU3MTg5LTU1NzdjN2M1LWYxNTgtNDZiZC1iOWU1LTRiODY2OWEwNGI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwNTQ4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZThhZmVkYjA3MTQ0NmZiMjRiMzhmNDM3M2U1Yzk3MzU5YjZmY2JlMTM0ZDA3MWEwZmY1ZjEzZDEwZThiZWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qWt2EJUabfYO8RyA9S8Ex2rgnTKjin6CHy_Wq7F-2d0)
> 
> more:
> 
> ```sql
> SELECT tokenid_utf8, count(*) cnt
> FROM owners
> WHERE expire_timestamp > UNIX_TIMESTAMP(NOW())
> GROUP BY tokenid_utf8
> HAVING	cnt > 1;
> ```
> 
> query result:
> 
> tokenid_utf8	cnt
> warirekyakiroeki🇮🇹	2
> ogun’omutimbaganogw’okugyezibwaobubonerotiburihomugasho	2
> wtf	2
> pepe	2
> northsat	2
> test	2
> sos	2
> makestampgreatagain	2
> bitname	2
> ibit	2
> javaeast	2
> jhakaaqueen	2
> styme	2
> aadil	2
> fight	2
> src	2
> mor	2
> muhammad	2
> nameless	2
> smoothieb	2
> ruby	2
> nra	2
> sea	2
> yara	2
> last	2
> dao	2
> presidentpepe	2
> run	2
> plan	2
> join	2
> swan	2
> su7	2
> gallery	2
> opeic	2
> I think it would better to replace `` UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid`), `` with `` UNIQUE KEY `p_deploy_hash_tokenid_unique` (`p`, `deploy_hash`, `tokenid_utf8`), ``, and the code needs to be adjusted accordingly.

https://github.com/stampchain-io/btc_stamps/pull/388
In this PR, we have added a new field, tokenid_origin, which is used to record the data submitted by users to the chain. tokenid and utf8 are already lowercase results, and there will no longer be a mismatch between tokenid and utf8.

**Comment by reinamora137** [comment]
fix merged
