### ISSUE TITLE
Branch `bitname/testnet` mint minted tokenid, data record tokenid and tokenid_utf8 fields are empty

### ISSUE THREAD

**Issue by btcopenstamp** [stampchain-io/btc_stamps#364]
**Describe the bug**
Send transaction mint minted tokenid, data record tokenid and tokenid_utf8 fields saved in SRC101 database table are empty.

**Branch/Release/Commit Hash of Problem**
Branch bitname/testnet.

**To Reproduce**
1. Using the mint operation to mint minted tokenid

**Expected behavior**
The tokenid of failed transaction records should also be recorded, which is more friendly for the application layer to query historical transactions.

**Comment by vikkkko** [comment]
Okay, we'll try to record this data as well
