### ISSUE TITLE
Branch `bitname/testnet` domain are case-sensitive

### ISSUE THREAD

**Issue by btcopenstamp** [stampchain-io/btc_stamps#372]
**Describe the bug**
Domain are case-sensitive.

**Branch/Release/Commit Hash of Problem**
Branch `bitname/testnet`.

**To Reproduce**
1. Minting both `topone` and `TopOne` can be successful.

**Expected behavior**
Domain should be case-insensitive..

**Comment by reinamora137** [comment]
fix merged
