### ISSUE TITLE
Branch `bitname/testnet` An exception occurs when the price field of the domain is `""`(blank characters) during deploy, resulting in the program terminating unexpectedly.

### ISSUE THREAD

**Issue by btcopenstamp** [stampchain-io/btc_stamps#432]
**Describe the bug**
An exception occurs when the price field of the domain is `""`(blank characters) during deploy, resulting in the program terminating unexpectedly.

**Branch/Release/Commit Hash of Problem**
Branch `bitname/testnet`.

**To Reproduce**
1. Deploy with price `""`(blank characters).

**Expected behavior**
The program can continue running without terminating.

**Screenshots**
```shell
Block: 3082036 (1.24s, hashes: L:N/A / TX:b9876 / M:ac6a2 / S:0 / S20:0)
Error in deploy operations: object of type 'NoneType' has no len()
An unexpected error occurred: object of type 'NoneType' has no len()
```

**Additional context**
1. Deploy information:
    ```
    {
        "p": "src-101",
        "op": "deploy",
        "root": "btc",
        "name": "Bit Name Service",
        "lim": "10",
        "owner": "tb1q3nyw4jlmvsczyz3xc3yqc7rr7nvxfnudp49laq",
        "rec": [
            "tb1q3nyw4jlmvsczyz3xc3yqc7rr7nvxfnudp49laq",
            "tb1qs2hmngp9lescxsd5pxj68en04v8w2guc7nlsa9"
        ],
        "tick": "BNS",
        "pri": "",
        "desc": "Bitname Service powered by BTC stamp.",
        "mintstart": "0",
        "mintend": "18446744073709551615",
        "wla": "0317ac27154373716ab3bce4f170211446e7598c69ae3a90f058c831c56308323c",
        "imglp": "https://testnet.img.bitname.pro/img/",
        "imgf": "btc.png",
        "idua": "999"
    }
    ```

2. The location where the code execution failed:
https://github.com/stampchain-io/btc_stamps/blob/f43eb41acab2302be0c5287aac35828bbbddb05c/indexer/src/index_core/src101.py#L375

Similarly, there are many scenarios of program robustness errors caused by missing fields or illegal fields that need further testing and improvement.

By the way, the test cases in src101 are still old codes that cannot be executed and need to be updated and maintained.

**Comment by vikkkko** [comment]
This is a bug and we will review the code again

**Comment by btcopenstamp** [comment]
Hi @vikkkko @reinamora137, please be aware that this issue could potentially cause the indexer to crash, based on our previous testing.

**Comment by reinamora137** [comment]
Definitely a good time for some test cases

**Comment by vikkkko** [comment]
This has been fixed
